### ISSUE TITLE
Task should pickup CF CLI from PATH when used in a release definition

### ISSUE THREAD

**Issue by seanmck** [Microsoft/vsts-cloudfoundry#1]
Currently it is only supported in build definitions.

**Comment by madhurig** [comment]
Fix: https://github.com/Microsoft/vsts-cloudfoundry/pull/4

**Comment by madhurig** [comment]
Released to the marketplace in version 0.115.0: https://marketplace.visualstudio.com/items?itemName=ms-vsts.cloud-foundry-build-extension
