### ISSUE TITLE
Inverted behavior for "Start on Deploy"

### ISSUE THREAD

**Issue by hensilva** [Microsoft/vsts-cloudfoundry#11]
If I mark the "Start on Deploy" option, CF command is issued with --no-start

If I unmarket the "Start on Deploy" option, CF command is issued without --no-start.

**Comment by Kreism** [comment]
We have the same problem. If the "Start On Deploy" is selected, the App will stay stopped
![image](https://user-images.githubusercontent.com/1275204/40356274-d9fab192-5db8-11e8-922f-d32bc482387d.png)
If we clear the selection, the apps are starting after deployment.

**Comment by davidstaheli** [comment]
A new version of the extension (1.136.0) with the fix has been published to the Visual Studio Marketplace.
