### ISSUE TITLE
Cloud Foundry CLI on the hosted build machines (hosted pipline) → Status?

### ISSUE THREAD

**Issue by jerzy-wachowiak** [Microsoft/vsts-cloudfoundry#14]
The README.md is already one year old. What is the current status of this

(...) We are looking into installing Cloud Foundry CLI on the hosted build machines or packaging it with the extension for the next release. (...)

**Comment by viperx77** [comment]
The cf cli should be automatically downloaded as part of the task.  At a minimum, the README.md must be updated to state the agent dependency.

**Comment by viperx77** [comment]
Why was this closed?  Is it fixed?
