### ISSUE TITLE
Allow cmdline overrides to provided manifest

### ISSUE THREAD

**Issue by seanmck** [Microsoft/vsts-cloudfoundry#2]
Currently, the task forces a choice between using a manifest and providing cmdline arguments manually. However, the CF CLI itself allows for both, with cmdline arguments overriding conflicting manifest values. Ideally, the VSTS task would mirror that behavior.

https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#precedence

**Comment by madhurig** [comment]
@seanmck: Additional arguments can be passed when specifying a manifest file or when specifying properties. Is this not sufficient?
![cfoptions](https://cloud.githubusercontent.com/assets/3269636/23414719/f35c768a-fdaa-11e6-968e-166dc7d5ed9d.png)

**Comment by seanmck** [comment]
I will double check - I can't remember if I tried that. Either way, I think it's useful to have first-class UI for the common parameters.

**Comment by madhurig** [comment]
@seanmck : Closing since overriding values from the manifest is possible. We can add more UI but it might be confusing and we can't add UI for all the common parameters anyway.
