### ISSUE TITLE
CLI Step not respecting the working directory option/variable 

### ISSUE THREAD

**Issue by mozts2005** [Microsoft/vsts-cloudfoundry#20]
Created PR #19  for the fix of this issue. 

added call to change to the working directory per the example on [line 91](https://github.com/Microsoft/vsts-cloudfoundry/blob/master/Extension/CloudFoundry/cloudfoundry.ts#L91) of the push step 
This issue is blocking my team per security rules only plugins from the marketplace are allowed

**Comment by mozts2005** [comment]
ETA?

**Comment by madhurig** [comment]
Thanks for your contribution. A new version (1.147.0) of the extension with this fix has been published. The changes will be automatically deployed to your Azure DevOps organization. Let us know if you see any issues.
