### ISSUE TITLE
error trying to add to VSTS org

### ISSUE THREAD

**Issue by siennathesane** [Microsoft/vsts-cloudfoundry#21]
To repro:

1. Selected the addon from the Visual Studio marketplace.
2. Clicked "Get it free"
3. Selected my org.
4. Hit install.

![image](https://user-images.githubusercontent.com/7537841/47544557-dbe11e80-d8a4-11e8-8d67-9831d39f3eef.png)

**Comment by mozts2005** [comment]
looks like you may already have the plugin installed in your organization.

**Comment by madhurig** [comment]
@mxplusb - are you still seeing this issue? We made a fix for this on the service in November.

**Comment by siennathesane** [comment]
No, I'm not still seeing it. Thanks checking.
