### ISSUE TITLE
sso option throws error

### ISSUE THREAD

**Issue by sbachuMSOL** [Microsoft/vsts-cloudfoundry#3]

**Comment by jpricket** [comment]
@sbachuMSOL - Could you provide more detail? like the error message that you get and what you set all the options to?

Thanks,
Jason

**Comment by sbachuMSOL** [comment]
Just fails -
with three "Authenticating... Credentials were rejected, please try again"
Finally - Unable to authenticate.

**Comment by madhurig** [comment]
@sbachuMSOL: This is a bug in the task. This option does not work in the CI system as it requires user response. Instead this should be changed to pass in a "single sign on passcode" that user has already acquired but it might not be that useful. We will include the fix in the next version of the task.

**Comment by madhurig** [comment]
Proposed fix : https://github.com/Microsoft/vsts-cloudfoundry/pull/4

**Comment by madhurig** [comment]
Ability to pass the one-time passcode released to the marketplace in version 0.115.0: https://marketplace.visualstudio.com/items?itemName=ms-vsts.cloud-foundry-build-extension
