### ISSUE TITLE
Need the ability for setting CF_HOME in the task

### ISSUE THREAD

**Issue by psgmurugan** [Microsoft/vsts-cloudfoundry#32]
We have a VSTS on a server which has around 4 agents. When this task logs in to CF it uses the location "<User>/.cf/config.json" as a semaphore to persist the session. If I login from an agent and start the release and parallelly if another release is going on, they both touch the same semaphore and results in conflict.

**Comment by lkillgore** [comment]
Fixed in 1.164.0.  Thanks @mozts2005!

**Comment by psgmurugan** [comment]
Thank you for the update
