### ISSUE TITLE
Allow cf options to be passed to the CLI

### ISSUE THREAD

**Issue by jeanmarc** [Microsoft/vsts-cloudfoundry#39]
The Cloud Foundry CLI task does not allow passing (global) options to the cf command, which makes it harder to debug stuff. For instance, we want to see the results of `cf CF_TRACE=true bgd`, but I see no way to provide this `CF_TRACE=true` flag.
Is it possible to add this to a future version of the Cloud Foundry CLI plugin?

**Comment by mozts2005** [comment]
CF_TRACE can also be enabled as an environment variable.

```yaml
variables:
- name: CF_TRACE
  value: true 

```

**Comment by jeanmarc** [comment]
Thanks for that workaround, it should be sufficient for our usecase.
